- name: My first play
  hosts: vps
  become: true
  tasks:
    - name: Ping my managed nodes
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Goodbye world
    - name: Install nginx on VPS
      ansible.builtin.apt:
        name: nginx

- name: My second play
  hosts: vm
  vars:
    ansible_become: true
    ansible_become_method: ansible.builtin.su
    ansible_become_password: " "
  tasks:
    - name: Ping my managed nodes
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Goodbye world
    - name: Install EPEL repo
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
    - name: Start the service
      ansible.builtin.service:
        name: nginx
        state: started
